### ISSUE TITLE
AWS Bottlerocket support

### ISSUE THREAD

**Issue by igorgolm** [XenitAB/spegel#222] opened 2023-10-09 12:53 UTC
Good day! 
Is it possible somehow configure spegel on AWS Bottlerocket nodes? If not - are you planning add this support? 
Thanks!

**Comment by tico24** [comment] 2023-10-10 06:13
https://github.com/XenitAB/spegel/issues/47

**Comment by bittrance** [comment] 2023-10-10 07:07
Closing as duplicate of #47.

**Closed by bittrance** 2023-10-10 07:07 UTC
Labels: duplicate, enhancement
