### ISSUE TITLE
failed to update all images: failed to walk image manifests: unexpected media type for digest

### ISSUE THREAD

**Issue by remram44** [XenitAB/spegel#172] opened 2023-08-17 17:54 UTC
I installed spegel `0.0.9` from Helm. It started on most of the nodes, but on some it failed:

> `{"level":"error","ts":1691505526.569151,"caller":"build/main.go:68","msg":"","error":"failed to update all images: failed to walk image manifests: unexpected media type  for digest: sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77","stacktrace":"main.main\n\t/build/main.go:68\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}`

I don't know how to troubleshoot this further.

**Comment by phillebaba** [comment] 2023-08-17 19:36
I realize that Spegel should probably not exit because of this, and instead just log and error. I will fix that so that Spegel keeps working.

Having said that I fixed a similar issue in #141 which was released as part of v0.0.9. Is this image public or private? If it is a public image could you share a link to it so I can have a look at the manifest.

**Comment by remram44** [comment] 2023-08-17 19:52
`crictl images --digests` doesn't list any such digest, I am not sure how to find which image it's from.

**Comment by phillebaba** [comment] 2023-08-17 20:02
It is probably not the digest of an image manifest but rather some other layer stored in `/var/lib/containerd/io.containerd.content.v1.content/blobs/sha256/`.

I have created #174 to minimize the effects of this error, as it is a reasonable solution for future issues. In that change I have also added some more information to the error message. It is getting a bit late here but I will try to get v0.0.11 released before I call it a night. Could you then upgrade and share the information that you see in the new logs?

**Comment by remram44** [comment] 2023-08-17 20:18
Yes I can try a new version. Take your time, I am not yet using spegel, this is not blocking or breaking anything on my end.

**Comment by phillebaba** [comment] 2023-08-17 20:29
There was a feature I wanted released anyways so you should be able to try it as soon as the release build completes.

**Comment by remram44** [comment] 2023-08-19 03:00
0.0.11 seems to work

**Comment by remram44** [comment] 2023-08-19 03:04
Here's the full log, there is still something in there about that digest, but it doesn't block successful operation:

> `{"level":"info","ts":1692412796.6450324,"logger":"p2p","caller":"routing/p2p.go:63","msg":"starting p2p router","id":"/ip4/10.0.83.124/tcp/5001/p2p/12D3KooWFHxqXB3HfvvfRUSCNr7M3gUgWq7LD4JaUepTTcNx9jRe"}`
> `{"level":"info","ts":1692412796.6452665,"caller":"build/main.go:169","msg":"running registry","addr":":5000"}`
> `I0819 02:39:56.645347       1 leaderelection.go:245] attempting to acquire leader lease spegel/spegel-leader-election...`
> `{"level":"info","ts":1692412796.6465182,"caller":"state/state.go:42","msg":"running scheduled image state update"}`
> `{"level":"error","ts":1692412796.8146071,"caller":"state/state.go:45","msg":"received errors when updating all images","error":"could not get digests for image quay.io/kubevirt/virtio-container-disk:latest@sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77: failed to walk image manifests: unexpected media type  for digest: sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77","stacktrace":"github.com/xenitab/spegel/internal/state.Track\n\t/build/internal/state/state.go:45\nmain.registryCommand.func4\n\t/build/main.go:150\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"}`
> `{"level":"info","ts":1692413336.6467876,"caller":"state/state.go:42","msg":"running scheduled image state update"}`
> `{"level":"error","ts":1692413336.8190713,"caller":"state/state.go:45","msg":"received errors when updating all images","error":"could not get digests for image quay.io/kubevirt/virtio-container-disk:latest@sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77: failed to walk image manifests: unexpected media type  for digest: sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77","stacktrace":"github.com/xenitab/spegel/internal/state.Track\n\t/build/internal/state/state.go:45\nmain.registryCommand.func4\n\t/build/main.go:150\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"}`
> `{"level":"info","ts":1692413876.6466143,"caller":"state/state.go:42","msg":"running scheduled image state update"}`
> `{"level":"error","ts":1692413876.813888,"caller":"state/state.go:45","msg":"received errors when updating all images","error":"could not get digests for image quay.io/kubevirt/virtio-container-disk:latest@sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77: failed to walk image manifests: unexpected media type  for digest: sha256:17e484fedc7ecaa8c83404aa85f0b615743ce723c05d3735436426f12d9e9c77","stacktrace":"github.com/xenitab/spegel/internal/state.Track\n\t/build/internal/state/state.go:45\nmain.registryCommand.func4\n\t/build/main.go:150\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"}`
> `{"level":"error","ts":1692413968.7060966,"caller":"gin@v0.0.9/logger.go:62","msg":"","path":"/v2/remram44/test20230818/manifests/2258","status":404,"method":"HEAD","latency":5.000618155,"ip":"10.33.69.9","handler":"mirror","error":"could not resolve mirror for key: quay.io/remram44/test20230818:2258","stacktrace":"github.com/xenitab/pkg/gin.Logger.func1\n\t/go/pkg/mod/github.com/xenitab/pkg/gin@v0.0.9/logger.go:62\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1995"}`
> `{"level":"info","ts":1692413969.179677,"caller":"state/state.go:49","msg":"received image event","image":"quay.io/remram44/test20230818:2258@sha256:023917ec6a886d0e8e15f28fb543515a5fcd8d938edb091e8147db4efed388ee"}`
> `{"level":"info","ts":1692413969.270584,"caller":"state/state.go:49","msg":"received image event","image":"quay.io/remram44/test20230818:2258@sha256:023917ec6a886d0e8e15f28fb543515a5fcd8d938edb091e8147db4efed388ee"}`
> `{"level":"info","ts":1692413969.295542,"caller":"state/state.go:49","msg":"received image event","image":"quay.io/remram44/test20230818"}`
> `{"level":"info","ts":1692413997.1634712,"caller":"gin@v0.0.9/logger.go:53","msg":"","path":"/v2/remram44/test20230818/manifests/2258","status":200,"method":"HEAD","latency":0.002628289,"ip":"10.32.250.13","handler":"manifest"}`

**Comment by avtakkar** [comment] 2023-08-22 18:50
I'm facing a similar error. In my case, the manifest is an OCI index, which does not have a top-level `mediaType` property that the code expects: https://github.com/XenitAB/spegel/blob/34817359ef2a99d1e1698066e7a74d0d820904ab/internal/oci/containerd.go#L146

**Comment by phillebaba** [comment] 2023-08-23 11:46
So I think I found the issue to this problem, the solution seems to be simple while the problem is a bit tricky. Thank you @avtakkar for the detail about media type it put me on the right track.

The issue originates from not reading the OCI spec properly. I assumed that `mediaType` was a required field in the index file, which is not.

> This property SHOULD be used and [remain compatible](https://github.com/opencontainers/image-spec/blob/main/media-types.md#compatibility-matrix) with earlier versions of this specification and with other similar external formats. When used, this field MUST contain the media type application/vnd.oci.image.index.v1+json. This field usage differs from the [descriptor](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#properties) use of mediaType.

https://github.com/opencontainers/image-spec/blob/main/image-index.md

This differs from the media type in the descriptor fields.
> This REQUIRED property contains the media type of the referenced content. Values MUST comply with [RFC 6838](https://tools.ietf.org/html/rfc6838), including the [naming requirements in its section 4.2](https://tools.ietf.org/html/rfc6838#section-4.2).

https://github.com/opencontainers/image-spec/blob/main/descriptor.md

I have not encountered index files that do not have the media type set, so I am a very interested to learn which tool neglects adding it.

The issue as stated is that my "naive" solution assumes that the media type is set in both index and manifest files. If you compare my solution to a similar one in Containerd you can see that the descriptor object is used instead to get the media type.
https://github.com/containerd/containerd/blob/738c15357380a6b7beb84be854fdd873a247ca56/images/image.go#L150
This means that Containerd is storing the media type of the "first" index of manifest for each image in its metadata db instead. As it is not possible to get that information another way.

I will create PR that fixes this issue, I just need to create an image that is missing the manifest type.

**Comment by phillebaba** [comment] 2023-08-23 21:20
I have a pretty good idea of how to work around reading content type from the file, my issue right now is finding or producing an image that lacks a manifest type. @avtakkar could you share the image that you were seeing the issue with?

**Comment by avtakkar** [comment] 2023-08-23 21:25
Sure, here's one.

```bash
curl -s -H "Accept: application/vnd.oci.image.index.v1+json" https://mcr.microsoft.com/v2/containernetworking/azure-cns/manifests/v1.4.44.2 | jq
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:6629ffde9bb46006b4920583e79787d38ebae15b09101b6e3d6c58acb2308c39",
      "size": 665,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:84287d603bc35b68ca54fb52baad613a34afe3962a2eb4635bc7db91454590c1",
      "size": 664,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:6114cc24bd5c45fd8d30140616b8a7b8f57fa32d0f66048ba89b492559f3dc70",
      "size": 819,
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.20348.643"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:7a3488b824c94f013bbf14dfedbd7414e3746b562b370af6c3dec98d37affb48",
      "size": 819,
      "platform": {
        "architecture": "amd64",
        "os": "windows",
        "os.version": "10.0.17763.4010"
      }
    }
  ]
}
```

**Comment by phillebaba** [comment] 2023-08-23 21:49
Thanks this is great for creating a test. I can see that for a matter of fact none of the layers has a media type set. Will use this image to verify image pulling works even with this image.

**Closed** 2023-08-24 12:21 UTC
Labels: bug
